### ISSUE TITLE
Button color 

### ISSUE THREAD

**Issue by sethu400** [Suvraneel/NFT-Emporium#15]
### Description

I can see the color of the buttons is not the same on every web page. Some buttons have hover effect. Text is not visible while hovering.

I'm thinking of making buttons more appealing with the web theme.

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Suvraneel/NFT-Emporium/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/Suvraneel/NFT-Emporium/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by sethu400** [comment]
Shall I start working on this issue? @Suvraneel

**Comment by Suvraneel** [comment]
@sethu400  Yes sure

**Comment by rharshit82** [comment]
Hi, Assign this issue to me.

**Comment by Suvraneel** [comment]
@sethu400  Unassigning after 26 days gap

@rharshit82  Go ahead

**Comment by nik132-eng** [comment]
if still this remains I want to work on this issue can you please assign it to me.

**Comment by Suvraneel** [comment]
@nik132-eng  Sure, go ahead

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by nik132-eng** [comment]
Sorry @Suvraneel  for disappointing you I don't even know how to install it on a local device. I have to learn moralis first so can I get some time for that??

**Comment by Suvraneel** [comment]
@nik132-eng Nope you don't need to learn anything for that...
No installation in reqd... Just clone the project & `npm i`...
Also install `MetaMask wallet` as browser extension for best usage (Altho not compulsory for your UI issues)

**Comment by Suvraneel** [comment]
@navyasharma0203  Since @nik132-eng  is already working on this, that wont be fair...
You can make your own issues & work on them once assigned.

The issues can be trivial or complex... Whatever you feel the website needs improvement in

**Comment by nik132-eng** [comment]
ok sir I will do it 👍
