### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by sethu400** [Suvraneel/NFT-Emporium#16]
### Description

Bugs are there to fix on the responsive web page.

### Type of Contribution

Enhancement

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Suvraneel/NFT-Emporium/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/Suvraneel/NFT-Emporium/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
@sethu Assigning responsiveness mainly

**Comment by rharshit82** [comment]
Hi, Assign me for the task

**Comment by TG922** [comment]
Is someone working on this issue??

**Comment by Suvraneel** [comment]
@rharshit82  Are you?

**Comment by nik132-eng** [comment]
**if still this remains I want to work on this issue can you please assign it to me.**

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by Raaghav4243** [comment]
Hi 
Please assign this issue to me, Reference: gssoc'22

**Comment by nik132-eng** [comment]
I can't get the project this time please assign this issue to the relevant person. Sorry for your inconvenience 😓
