### ISSUE TITLE
Navbar UI

### ISSUE THREAD

**Issue by Suvraneel** [Suvraneel/NFT-Emporium#17]
### Description

Make the Navbar UI more appealing.
Currently it is default from an ethreum boilerplate

### Type of Contribution

Enhancement, UI/UX

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Suvraneel/NFT-Emporium/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/Suvraneel/NFT-Emporium/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by shivam123-dev** [comment]
@Suvraneel I can make Navbar UI like this:-
![image](https://user-images.githubusercontent.com/81038095/161132252-13b7d433-82e3-4e73-a531-48f0625aaa74.png)

Are there any suggestions on this Navbar UI or should I convert the existing Navbar UI into this? Being a GSSOC'22 participant. Kindly assign me this issue

**Comment by Suvraneel** [comment]
@shivam123-dev  

That's just the opacity & color of the button bro...
You'll need to design something that goes well with background... 
Maybe throw in a hover & focus effects as well...
Its pretty straightforward. I built it in a 5day hackathon, so couldnt give much attention to UI... Now there's much room for improvement... Go ahead

**Comment by gurjeetsinghvirdee** [comment]
Assign me @Suvraneel
